# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Carmona
url: https://danielcarmona.me
author: Daniel Carmona Serrat
email: daniel@carmona.email
github_username: MrPolymath
repository: mrpolymath/mrpolymath.github.io
description: > # this means to ignore newlines until "baseurl:"
  This blog has been conceived as a way of telling the world all the adventures that I have been through
  ever since I started university and founded my first company as well as to explain my day-to-day life and future projects and ideas that I'm working on.
  I hope all my previous experience can
  help others and hopefully entertain all of you, because that is a real roller coaster of events.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MrPolymath
comments: true
disqus:
  shortname: danielcarmona

# Build settings
markdown: kramdown
theme: minima
future: false
plugins_dir:
  - jekyll-feed

gems:
  - jemoji
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
